fix: add missing Electron files in the nuget template
electron/windows-installer pull request #367
Opened 2020-11-17 18:11 UTC by ChALkeR

This adds `swiftshader` dir and the `vk_swiftshader_icd.json` file into the package template, so that they would be included into the distribution.

Without `swiftshader` dir, Electron crashes with "Failed to launch GPU process" error on some setups.

To reproduce: build an installer, run in a Windows VM with GPU acceleration disabled.
Alternatively: with no vendor GPU drivers installed, just the default Microsoft one.

2020-12-04 18:10 UTC, malept requested changes
I'd like to merge this but the tests are failing. Can you please fix those?

2020-12-14 14:03 UTC, basz commented
is this stalling for a reason?

2020-12-14 16:12 UTC, malept commented
@basz see https://github.com/electron/windows-installer/pull/367#pullrequestreview-545187013

2020-12-17 11:57 UTC, chetbox commented
Can @ChALkeR or anyone else suggest why this is failing and what needs to be done? We're keen to see this fixed given it affects anyone installing an Electron 10 app on Windows, via the Squirrel Installer, which is the recommend installer. (See https://github.com/electron-userland/electron-forge/issues/1955)

We've found this to be a affect users of VMs with no video hardware acceleration (a vanilla VirtualBox VM in this case) and also when remotely logged into machines via Teamviewer.

2020-12-23 21:33 UTC, martinellimarco commented
As a random user, I've tested it and it does work. If you read the details of the failure it seems it has nothing to do with the actual change. My 2 cent is that this is a problem with the CI setup, maybe someone should check that or try to run the tests again.

2020-12-23 21:44 UTC, malept commented
I haven't looked in detail, but I suspect that this change will fail with older versions of Electron that do not contain the swiftshader files. This module doesn't currently specify the versions of Electron that it supports, so it effectively supports pretty much all versions. If we restrict that, this will require a major version bump. Otherwise the change will need to be fixed so that it works for versions without these files.

2021-01-18 17:30 UTC, zac-jacobson commented
A workaround we found is, if you don't actually **need** hardware acceleration, to turn it off.
https://www.electronjs.org/docs/tutorial/offscreen-rendering#rendering-modes

2021-01-19 16:43 UTC, niik commented
:wave: We (the GitHub Desktop team) is looking into [upgrading to Electron 11](https://github.com/desktop/desktop/pull/11142) and came upon this issue which made us a tad bit nervous as it seems like it would affect Electon 11 as well (right?).

We'd be happy to help in any way we can to get this over the finish line but it's not immediately obvious how.

> I haven't looked in detail, but I suspect that this change will fail with older versions of Electron that do not contain the swiftshader files. This module doesn't currently specify the versions of Electron that it supports, so it effectively supports pretty much all versions. If we restrict that, this will require a major version bump. Otherwise the change will need to be fixed so that it works for versions without these files.

@malept Do you have a sense of what your preferred approach would be?

In case the approach would be to special case versions prior to Electron 10 do you envision having two different `nuspecttemplate` files and conditionally including one or the other?

https://github.com/electron/windows-installer/blob/7f6ea867cb54aaa2bb0a2973641198cc8e05a43a/src/index.ts#L107

Or would you rather attempt to add the entries to the existing template at runtime?

And last question (for now), what method would you prefer for detecting whether these files need to be included? Should we just check whether they exist in the `appDirectory` or would you like to specifically check the bundled electron version?

2021-01-19 19:37 UTC, malept commented
> Or would you rather attempt to add the entries to the existing template at runtime?

I would prefer changing the existing template at runtime so that we don't have to potentially maintain two slightly different templates, but if it ends up being too much work, I guess we'll have to deal with it.

> And last question (for now), what method would you prefer for detecting whether these files need to be included? Should we just check whether they exist in the `appDirectory` or would you like to specifically check the bundled electron version?

That is a good question. Try checking for existence first, and if that ends up being too complicated, let's talk about checking the Electron version.

2021-02-10 17:19 UTC, closed without merging