fix: Corrected the verification of Mono and Wine installation status
electron/windows-installer pull request #488
Opened 2023-10-23 06:33 UTC by BitYoungjae

The old code wrongly checked if Mono and Wine were installed. It looked like this:

https://github.com/electron/windows-installer/blob/073930d4845432adb2f16891c81066249cf99c71/src/index.ts#L26-L40

The part `(!wineExe || !monoExe)` didn't work right because wineExe and monoExe were just text, not real checks.

Now, the code really checks if Wine and Mono are there. This fix makes sure the setup works right and checks everything needed.

2023-10-23 07:33 UTC, BlackHole1 requested changes

2023-10-23 07:33 UTC, BlackHole1 commented on src/index.ts
> +    const isMonoInstalled = await checkIfCommandExists(monoExe);
```suggestion
    const [hasWine,hasMono] = await Promise.all([
      checkIfCommandExists(wineExe),
      checkIfCommandExists(monoExe),
    ]);
```

2023-10-23 09:01 UTC, BitYoungjae commented on src/index.ts
> +    const isMonoInstalled = await checkIfCommandExists(monoExe);
Made the changes you suggested. Thanks!

2023-10-23 10:57 UTC, BlackHole1 approved these changes
LGTM. PTAL @electron/wg-ecosystem

2023-10-24 04:01 UTC, dsanders11 approved these changes

2023-10-24 06:32 UTC, merged