chore: remove semver dependency
electron/windows-installer pull request #534
Opened 2024-09-19 22:57 UTC by rtritto

Simplify logic to check Node version and remove `semver` use.

Fix #516

2024-09-19 23:49 UTC, erickzhao requested changes
Hi @rtritto, thanks for the PR. I think we should instead just add semver as a dep here instead of manually parsing the version string.

We already have `semver` in our lockfile a couple times, so I think this would be the correct invocation:

```sh
yarn add semver
npx uuaw semver
```

2024-09-20 06:58 UTC, rtritto commented
It's better to have less dependencies to reduce version checks and to improve performance, bundle and readability.
In the future, `semver` could be removed from other dependencies and, with this change, we won't change nothing.

2024-09-20 18:55 UTC, erickzhao commented
> It's better to have less dependencies to reduce version checks and to improve performance, bundle and readability.

I disagree here. SemVer logic isn't always trivial and having to write individual string parsing functions for each case doesn't make a lot of sense.

It's also a first-party npm package that's used across the ecosystem (for example, we already have a few other instances of `semver` in this project's lockfile via tooling such as `typescript-eslint`).

2024-09-20 19:22 UTC, MarshallOfSound commented
Agree with Erick above, also worth noting that this code as it stands is wrong. Difference checks between numbers and strings do not work as you'd expect.

Keep the semver dependency

2024-09-20 22:22 UTC, rtritto commented
> Agree with Erick above, also worth noting that this code as it stands is wrong. Difference checks between numbers and strings do not work as you'd expect.

You're right, I forgot the compare as numbers.

Opened #535

2024-09-20 22:22 UTC, closed without merging